apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
   app: app-config
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 3
  replicas: 6
  selector:
    matchLabels:
         app: app-config
  template:
    metadata:
      labels:
        app: app-config
    spec:
     containers:
     - name: app-config
       image: alejandraestacio/app-config:1
       ports:
        - containerPort: 8888

---

kind: Service
apiVersion: v1
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: app-config
  ports:
   - protocol: TCP
     port: 8888
     targetPort: 8888